# Generated by Django 2.1.5 on 2019-04-30 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='media/images/%Y/%m/%d'),
        ),
    ]
